# Etapa de Build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa de Produção
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Copia a configuração do Nginx configurada para React Router e Proxy API
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
